/**
 * Stable aliases over the schema-generated ERC-7730 v2 input model.
 *
 * Source of truth: `src/schema/official/erc7730-v2.schema.json`
 * Regenerated by: `pnpm schema:types`
 */

export type {
  ERC7730V2Context,
  ERC7730V2Metadata,
  ERC7730V2Display,
  ERC7730V2FieldFormat,
  ERC7730V2OwnerInfo,
  TokenDescription,
  DisplayField,
  FieldGroup,
  FieldReference,
  FieldParams,
  DisplayRule,
  DisplayIntent,
  EncryptionParameters,
  MapReference,
  ContractBindingContext,
  EIP712Binding,
  FactoryConstraint,
  DeploymentList,
  Enumeration,
  ConstantValues,
  Enums,
  AStructuredDataFormatSpecification,
  DisplayFieldItemList,
} from './generated/erc7730-v2';

import type { InputDescriptor } from './descriptor';
import type {
  AStructuredDataFormatSpecification,
  DisplayField,
  DisplayFieldItemList,
  DisplayIntent,
  Enumeration,
} from './generated/erc7730-v2';

/** @deprecated Use {@link InputDescriptor}. */
export type ERC7730V2Descriptor = InputDescriptor;

/** Display format entry under `display.formats`. */
export type DisplayFormat = AStructuredDataFormatSpecification;

/** One item in a format `fields` array. */
export type DisplayFieldItem = NonNullable<DisplayFieldItemList>[number];

/** Intent string or locale map. */
export type Intent = DisplayIntent;

/** Enum map under `metadata.enums`. */
export type EnumDefinition = Enumeration;

/** @deprecated Prefer {@link DisplayField}. */
export type FieldFormatter = DisplayField;
